version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: darukaa_postgis
    environment:
      POSTGRES_USER: darukaa_user
      POSTGRES_PASSWORD: darukaa_password
      POSTGRES_DB: darukaa_db
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: darukaa_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://darukaa_user:darukaa_password@db:5432/darukaa_db
      - JWT_SECRET_KEY=darukaa_earth_hackathon_super_secret_2026
    depends_on:
      - db

volumes:
  postgis_data:
